# Random Forest

### Importing packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score, KFold

### Reading dataset

In [2]:
df = pd.read_csv(r"E:\medical hackathon\heart_training.csv")

In [3]:
df.head()

Name  Gender  Age  Chest pain  Shortness of breath  Fatigue  \
0          Jane Doe  Female   55           1                    1        1   
1      Mark Johnson    Male   57           1                    1        1   
2       Emily Davis  Female   60           1                    1        1   
3  William Thompson    Male   62           1                    1        1   
4    Ashley Johnson  Female   58           1                    1        1   

   Systolic  Diastolic  Heart rate (bpm)  Lung sounds  ...  \
0       140         90               100            1  ...   
1       150         80               110            1  ...   
2       130         85                95            1  ...   
3       145         90               100            1  ...   
4       135         80               105            1  ...   

                                          Cardiac CT  Obesity  Murmur  \
0  Shows a 50% blockage in the left anterior desc...        0       1   
1  Shows a 60% blockage in the right coronary artery        0       1   
2  Shows a 75% blockage in the left anterior desc...        0       1   
3  Shows a 80% blockage in the left circumflex co...        0       1   
4  Shows a 90% blockage in the right coronary artery        0       1   

   Chest x-ray  Previous illnesses  Pulmonary function tests  Spirometry  \
0            0                   0                         0           0   
1            0                   0                         0           0   
2            0                   0                         0           0   
3            0                   0                         0           0   
4            0                   0                         0           0   

                       Diagnosis                        Medications  Treatment  
0  Coronary artery disease (CAD)  Aspirin, metoprolol, atorvastatin          0  
1  Coronary artery disease (CAD)    Aspirin, ramipril, atorvastatin          0  
2  Coronary artery disease (CAD)  Aspirin, lisinopril, rosuvastatin          0  
3  Coronary artery disease (CAD)  Aspirin, metoprolol, atorvastatin          0  
4  Coronary artery disease (CAD)   Aspirin, simvastatin, lisinopril          0  

[5 rows x 49 columns]

### Label Encoding

In [4]:
df.replace({'Gender':{"Male":0,"Female":1}},inplace=True)
df.replace({'Echocardiogram':{"Shows increased pressure in the right ventricle":1,"Shows increased pressure in the right ventricle and decreased function of the right ventricle":2,"Shows vegetation on the aortic valve":3,"Shows vegetation on the aortic valve and pulmonic valve":4,"Shows vegetation on the mitral valve":5,"Shows vegetation on the mitral valve and aortic valve":6,"Shows vegetation on the mitral valve and pulmonary valve":7,"Shows vegetation on the mitral valve and tricuspid valve":8,"Shows vegetation on the mitral valve, aortic valve and tricuspid valve":9,"Shows vegetation on the mitral valve, aortic valve, and pulmonary valve":10,"Shows vegetation on the mitral valve, aortic valve, tricuspid valve, and pulmonary valve":11,"Shows vegetation on the mitral valve, tricuspid valve, and pulmonary valve":12,"Shows vegetation on the pulmonary valve":13,"Shows vegetation on the tricuspid valve":14,"Shows vegetation on the tricuspid valve and pulmonary valve":15, "Shows increased pressure in the right ventricle and decreased function of the left ventricle":16}},inplace=True)
df.replace({'Blood culture':{"Positive for Candida albicans":1,"Positive for Candida dubliniensis":2,"Positive for Candida glabrata":3,"Positive for Candida guilliermondii":4,"Positive for Candida krusei":5,"Positive for Candida lusitaniae":6,"Positive for Candida parapsilosis":7,"Positive for Candida rugosa":8,"Positive for Candida tropicalis":9,"Positive for Enterococcus faecalis":10,"Positive for Staphylococcus aureus":11,"Positive for Staphylococcus epidermidis":12,"Positive for Streptococcus anginosus":13,"Positive for Streptococcus bovis":14,"Positive for Streptococcus mitis":15,"Positive for Streptococcus oralis":16,"Positive for Streptococcus pneumonia":17,"Positive for Streptococcus pneumoniae":18,"Positive for Streptococcus salivarius":19,"Positive for Streptococcus sanguinis":20,"Positive for Streptococcus viridans":21
}},inplace=True)
df.replace({'EKG':{"Abnormal":1,"Normal":2,"Shows an elevated ST segment and PR interval consistent with pericarditis":3,"Shows atrial fibrillation":4,"Shows diffuse ST depression and PR elevation consistent with pericarditis":5,"Shows electrical alternans consistent with pericarditis":6,"Shows evidence of aortic stenosis":7,"Shows evidence of aortic valve regurgitation":8,"Shows evidence of arrhythmogenic right ventricular cardiomyopathy":9,"Shows evidence of atrial fibrillation and left ventricular hypertrophy":10,"Shows evidence of atrial fibrillation and valve regurgitation":11,"Shows evidence of dilated cardiomyopathy":12,"Shows evidence of endocarditis":13,"Shows evidence of hypertrophic cardiomyopathy":14,"Shows evidence of left bundle branch block":15,"Shows evidence of left bundle branch block and left ventricular hypertrophy":16,"Shows evidence of left ventricular dysfunction and valve regurgitation":17,"Shows evidence of left ventricular hypertrophy":18,"Shows evidence of left ventricular hypertrophy and atrial fibrillation":19,"Shows evidence of left ventricular hypertrophy and left atrial enlargement":20,"Shows evidence of left ventricular hypertrophy and ST-segment depression":21,"Shows evidence of left ventricular hypertrophy and ST-segment elevation":22,"Shows evidence of mitral regurgitation":23,"Shows evidence of mitral regurgitation and atrial fibrillation":24,"Shows evidence of mitral stenosis":25,"Shows evidence of mitral valve regurgitation":26,"Shows evidence of pericarditis":27,"Shows evidence of pericarditis and atrial fibrillation":28,"Shows evidence of pericarditis and left atrial enlargement":29,"Shows evidence of pericarditis and left bundle branch block":30,"Shows evidence of pericarditis and left ventricular hypertrophy":31,"Shows evidence of pericarditis and right bundle branch block":32,"Shows evidence of pericarditis and right ventricular hypertrophy":33,"Shows evidence of pericarditis and sinus tachycardia":34,"Shows evidence of pericarditis and valve regurgitation":35,"Shows evidence of pulmonary stenosis":36,"Shows evidence of restrictive cardiomyopathy":37,"Shows evidence of right bundle branch block":38,"Shows evidence of right bundle branch block and left ventricular hypertrophy":39,"Shows evidence of ST-segment depression in leads II, III, and aVF":40,"Shows evidence of Takotsubo cardiomyopathy":41,"Shows evidence of tricuspid stenosis":42,"Shows evidence of tricuspid valve regurgitation":43,"Shows evidence of T-wave inversion in leads V1-V4":44,"Shows left bundle branch block":45,"Shows left ventricular hypertrophy":46,"Shows low voltage QRS consistent with pericarditis":47,"Shows sinus tachycardia":48,"Shows sinus tachycardia and diffuse ST elevation consistent with pericarditis":49,"Shows ST-segment elevation":50}},inplace=True)
df.replace({'Cardiac CT':{"Shows a 100% dilation of the proximal aorta":1,"Shows a 110% dilation of the proximal aorta":2,"Shows a 120% dilation of the proximal aorta":3,"Shows a 130% dilation of the proximal aorta":4,"Shows a 25% dilation of the infrarenal aorta":5,"Shows a 30% dilation of the abdominal aorta":6,"Shows a 30% dilation of the infrarenal aorta":7,"Shows a 35% dilation of the infrarenal aorta":8,"Shows a 38% dilation of the infrarenal aorta":9,"Shows a 40% dilation of the abdominal aorta":10,"Shows a 40% dilation of the infrarenal aorta":11,"Shows a 40% dilation of the thoracic aorta":12,"Shows a 40% dilation of the thoracoabdominal aorta":13,"Shows a 42% dilation of the infrarenal aorta":14,"Shows a 45% dilation of the infrarenal aorta":15,"Shows a 45% dilation of the thoracic aorta":16,"Shows a 50% blockage in the left anterior descending coronary artery":17,"Shows a 50% dilation of the abdominal aorta":18,"Shows a 50% dilation of the proximal aorta":19,"Shows a 50% dilation of the thoracic aorta":20,"Shows a 50% dilation of the thoracoabdominal aorta":21,"Shows a 55% dilation of the proximal aorta":22,"Shows a 55% dilation of the thoracic aorta":23,"Shows a 60% blockage in the left main coronary artery":24,"Shows a 60% blockage in the right coronary artery":25,"Shows a 60% dilation of the abdominal aorta":26,"Shows a 60% dilation of the proximal aorta":27,"Shows a 60% dilation of the thoracic aorta":28,"Shows a 60% dilation of the thoracoabdominal aorta":29,"Shows a 65% dilation of the thoracic aorta":30,"Shows a 70% blockage in the left anterior descending coronary artery":31,"Shows a 70% blockage in the right coronary artery":32,"Shows a 70% dilation of the abdominal aorta":33,"Shows a 70% dilation of the proximal aorta":34,"Shows a 70% dilation of the thoracic aorta":35,'Shows a 70% dilation of the thoracoabdominal aorta':36,"Shows a 75% blockage in the left anterior descending coronary artery":37,"Shows a 75% dilation of the thoracic aorta":38,"Shows a 80% blockage in the left circumflex coronary artery":39,"Shows a 80% dilation of the proximal aorta":40,"Shows a 80% dilation of the thoracoabdominal aorta":41,"Shows a 80% dilation of the thoracoabdominal aorta":42,"Shows a 90% blockage in the right coronary artery":43,"Shows a 90% dilation of the proximal aorta":44,"Shows a 90% dilation of the thoracic aorta":45,"Shows a 90% dilation of the thoracoabdominal aorta":46,"Shows a mild dilatation in the left ventricle":47,"Shows a mild dysfunction of the left ventricle":48,"Shows a mild dysfunction of the right ventricle":49,"Shows a mild hypertrophy in the left ventricle":50,"Shows a mild regurgitation in the mitral valve":51,"Shows a mild restriction in the ventricular filling":52,"Shows a mild stenosis in the mitral valve":53,"Shows a mild stenosis in the pulmonary valve":54,"Shows a mild stenosis in the tricuspid valve":55,"Shows a moderate dilatation in the left ventricle":56,"Shows a moderate dysfunction of the left ventricle":57,"Shows a moderate dysfunction of the right ventricle":58,"Shows a moderate hypertrophy in the left ventricle":59,"Shows a moderate hypertrophy in the right ventricle":60,"Shows a moderate regurgitation in the mitral valve":61,"Shows a moderate restriction in the ventricular filling":62,"Shows a moderate stenosis in the aortic valve":63,"Shows a moderate stenosis in the mitral valve":64,"Shows a moderate stenosis in the pulmonary valve":65,"Shows a moderate stenosis in the tricuspid valve":66,"Shows a severe dilatation in the left ventricle":67,"Shows a severe dysfunction of the left ventricle":68,"Shows a severe dysfunction of the right ventricle":69,"Shows a severe hypertrophy in the left ventricle":70,"Shows a severe hypertrophy in the right ventricle":71,"Shows a severe regurgitation in the mitral valve":72,"Shows a severe restriction in the ventricular filling":73,"Shows a severe stenosis in the aortic valve":74,"Shows a severe stenosis in the mitral valve":75,"Shows a severe stenosis in the tricuspid valve":76,"Shows constrictive pericarditis":77,"Shows effusion in the pericardium":78,"Shows pericardial effusion and tamponade":79,"Shows pericarditis with myocarditis":80,"Shows thickening of the pericardium":81}},inplace=True)
df.replace({'Chest x-ray':{"Shows hyperinflation and bronchial wall thickening":1,"Shows hyperinflation, bronchial wall thickening, and increased vascular markings":2,"Shows increased vascular markings and signs of chronic changes in the lungs":3,"Shows increased vascular markings and signs of lung restriction":4,"Shows increased vascular markings and small areas of consolidation in the lungs":5,"Shows increased vascular markings and small areas of fibrosis in the lungs":6,"Shows increased vascular markings in the lungs":7,"Shows increased vascular markings in the lungs, small areas of fibrosis, and signs of lung restriction":8,"Shows increased vascular markings, small areas of fibrosis and signs of lung restriction":9,"Shows increased vascular markings, small areas of fibrosis, and signs of chronic changes in the lungs":10,"Shows increased vascular markings, small areas of fibrosis, and signs of lung restriction":11,"Shows normal lung structures with no obvious abnormalities":12}},inplace=True)
df.replace({'Previous illnesses':{"Aortic valve replacement surgery":1,"Mitral valve replacement surgery":2,"Recent chest surgery":3,"Recent viral infection":4,"Tricuspid valve replacement surgery":5}},inplace=True)
df.replace({'Pulmonary function tests':{"Shows decreased lung capacity":1,"Shows decreased lung capacity and reduced diffusing capacity of the lung for carbon monoxide":2,"Shows decreased lung capacity, reduced diffusing capacity of the lung for carbon monoxide and decreased lung volumes":3,"Shows normal lung capacity":4}},inplace=True)
df.replace({'Spirometry':{"Shows decreased lung function and increased airway resistance":1}},inplace=True)
df.replace({'Diagnosis':{'Coronary artery disease (CAD)':0, 'Mitral regurgitation':1, 'Mitral stenosis':2, 'Aortic stenosis':3, 'Tricuspid stenosis':4,'Pulmonary stenosis':5, 'Dilated cardiomyopathy':6, 'Hypertrophic cardiomyopathy':7, 'Restrictive cardiomyopathy':8,'Arrhythmogenic right ventricular cardiomyopathy':9, 'Takotsubo cardiomyopathy':10, 'Thoracic aortic aneurysm':11, 'Abdominal aortic aneurysm':12,'Proximal aortic aneurysm':13, 'Infrarenal aortic aneurysm':14, 'Thoracoabdominal aortic aneurysm':15, 'Acute pericarditis':16, 'Chronic pericarditis':17,'Constrictive pericarditis':18, 'Pericardial effusion with tamponade':19, 'Pericarditis with myocarditis':20, 'Acute native valve endocarditis':21,'Subacute native valve endocarditis':22, 'Infective endocarditis on prosthetic valve':23, 'Candidal endocarditis':24, 'Native valve endocarditis involving multiple valves':25,'Primary pulmonary hypertension':26, 'Secondary pulmonary hypertension due to COPD':27, 'Secondary pulmonary hypertension due to obesity and sleep apnea':28, 'Secondary pulmonary hypertension due to scleroderma':29,'Secondary pulmonary hypertension due to chronic thromboembolic disease':30}},inplace=True)


df.tail(20)

df.to_csv(r"E:\medical hackathon\preprocessed_heart_training.csv", index=False)

In [5]:
df.tail()

Name  Gender  Age  Chest pain  Shortness of breath  Fatigue  \
319      Sara Smith       1   60           1                    1        1   
320  James Williams       0   65           1                    1        1   
321  David Thompson       0   60           1                    1        1   
322         Kim Lee       1   55           1                    1        1   
323   Liam Thompson       0   50           1                    1        1   

     Systolic  Diastolic  Heart rate (bpm)  Lung sounds  ...  Cardiac CT  \
319       130         80               120            1  ...           0   
320       130         80               110            1  ...           0   
321       140         90               120            1  ...           0   
322       130         80               100            1  ...           0   
323       130         80               110            1  ...           0   

     Obesity  Murmur  Chest x-ray  Previous illnesses  \
319        0       0            0                   1   
320        0       0            0                   2   
321        0       0            0                   1   
322        0       0            0                   2   
323        0       0            0                   1   

     Pulmonary function tests  Spirometry  Diagnosis              Medications  \
319                         0           0         23    Oxacillin, vancomycin   
320                         0           0         23     Vancomycin, rifampin   
321                         0           0         23   Vancomycin, gentamicin   
322                         0           0         23      Nafcillin, rifampin   
323                         0           0         23  Amoxicillin, gentamicin   

     Treatment  
319          0  
320          0  
321          0  
322          0  
323          0  

[5 rows x 49 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 49 columns):
 #   Column                                           Non-Null Count  Dtype 
---  ------                                           --------------  ----- 
 0   Name                                             324 non-null    object
 1   Gender                                           324 non-null    int64 
 2   Age                                              324 non-null    int64 
 3   Chest pain                                       324 non-null    int64 
 4   Shortness of breath                              324 non-null    int64 
 5   Fatigue                                          324 non-null    int64 
 6   Systolic                                         324 non-null    int64 
 7   Diastolic                                        324 non-null    int64 
 8   Heart rate (bpm)                                 324 non-null    int64 
 9   Lung sounds                                

### Checking for null values

In [1]:
df.isnull().sum()

NameError: name 'df' is not defined

### Counting the number of datas for different Diagnosis

In [8]:
df['Diagnosis'].value_counts()

30    12
21    12
29    12
24    12
20    12
22    12
19    11
14    11
13    11
12    11
23    11
17    11
25    11
26    11
27    11
28    11
16    11
0     10
1     10
11    10
10    10
9     10
8     10
7     10
6     10
5     10
4     10
3     10
2     10
15    10
18     1
Name: Diagnosis, dtype: int64

### Splitting the input and target values

In [9]:
# iloc: takes interger values of [rows, columns]
X = df.iloc[:, 1:46]

# taking second last column
y = df.iloc[:, -3]

In [10]:
X.head()

Gender  Age  Chest pain  Shortness of breath  Fatigue  Systolic  Diastolic  \
0       1   55           1                    1        1       140         90   
1       0   57           1                    1        1       150         80   
2       1   60           1                    1        1       130         85   
3       0   62           1                    1        1       145         90   
4       1   58           1                    1        1       135         80   

   Heart rate (bpm)  Lung sounds  Cholesterol level (mg/dL)  ...  \
0               100            1                        220  ...   
1               110            1                        210  ...   
2                95            1                        230  ...   
3               100            1                        240  ...   
4               105            1                        220  ...   

   Echocardiogram  Blood culture  EKG  Cardiac CT  Obesity  Murmur  \
0               0              0   18          17        0       1   
1               0              0   18          25        0       1   
2               0              0   18          37        0       1   
3               0              0   18          39        0       1   
4               0              0   18          43        0       1   

   Chest x-ray  Previous illnesses  Pulmonary function tests  Spirometry  
0            0                   0                         0           0  
1            0                   0                         0           0  
2            0                   0                         0           0  
3            0                   0                         0           0  
4            0                   0                         0           0  

[5 rows x 45 columns]

In [11]:
y.tail()

319    23
320    23
321    23
322    23
323    23
Name: Diagnosis, dtype: int64

In [12]:
X.shape

(324, 45)

In [13]:
y.shape

(324,)

### Splitting the data for train and test

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.2)

### Use of Random Forest Classifier

In [16]:
ranforcls = RandomForestClassifier(criterion = "gini", max_depth= 8, min_samples_split = 10, random_state = 42)

In [17]:
ranforcls.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=42)

In [18]:
ranforcls.feature_importances_

array([0.00532475, 0.02853656, 0.00821836, 0.00735914, 0.00229527,
       0.02506136, 0.02247648, 0.03188225, 0.01134624, 0.01068276,
       0.01674867, 0.0161074 , 0.        , 0.00025349, 0.03531597,
       0.01120234, 0.03142945, 0.03323848, 0.01903755, 0.03116609,
       0.02171223, 0.01131233, 0.0313418 , 0.02163877, 0.01068411,
       0.00264593, 0.034891  , 0.02364096, 0.01223986, 0.        ,
       0.01120432, 0.01724633, 0.02171574, 0.01506019, 0.0040509 ,
       0.04854765, 0.05468491, 0.06143009, 0.06248691, 0.0129784 ,
       0.02396414, 0.04870039, 0.03022878, 0.04352512, 0.0263865 ])

In [19]:
X.columns

Index(['Gender', 'Age', 'Chest pain', 'Shortness of breath', 'Fatigue',
       'Systolic', 'Diastolic', 'Heart rate (bpm)', 'Lung sounds',
       'Cholesterol level (mg/dL)', 'LDL level (mg/dL)', 'HDL level (mg/dL)',
       'Diabetes', 'Atrial fibrillation', 'Mitral valve prolapse',
       'Rheumatic fever', 'Mitral stenosis', 'Aortic stenosis',
       'Tricuspid stenosis', 'Pulmonary stenosis', 'Dilated cardiomyopathy',
       'Hypertrophic cardiomyopathy', 'Restrictive cardiomyopathy',
       'Arrhythmogenic right ventricular cardiomyopathy',
       'Takotsubo cardiomyopathy', 'Drug use', 'Fever', 'Chills', 'Joint pain',
       'Alcoholism', 'Hypertension', 'Fainting', 'Dizziness', 'Smoking',
       'High cholesterol', 'Echocardiogram', 'Blood culture', 'EKG',
       'Cardiac CT', 'Obesity', 'Murmur', 'Chest x-ray', 'Previous illnesses',
       'Pulmonary function tests', 'Spirometry'],
      dtype='object')

In [20]:
y_pred = ranforcls.predict(X_test)

In [21]:
y_pred

array([13, 10, 13, 13, 20, 12, 24, 21, 28, 15, 20, 19, 22, 12, 20, 14, 16,
       13,  2, 13, 14, 29,  4,  8,  9, 16, 22,  7,  6, 23,  9, 22, 27, 19,
       19, 19,  5,  3, 10,  2, 20,  4, 14, 27,  4, 17, 19, 29,  5,  1,  7,
       10, 14,  7,  7, 30, 28, 26, 13, 15, 10, 25,  6,  9, 28],
      dtype=int64)

In [23]:
y_test

132    13
108    10
137    13
9       0
180    20
       ..
104    10
231    25
60      6
94      9
265    28
Name: Diagnosis, Length: 65, dtype: int64

### Checking the accuracy of our model

In [24]:
accuracy_score(y_test, y_pred)

0.7846153846153846

### Checking the accuracy of each folds of the model ( 6 different folds )

In [25]:
kf = KFold(n_splits = 6, shuffle= True, random_state=42)

cv_scores = cross_val_score(ranforcls, X_train, y_train, cv=kf)

In [26]:
cv_scores

array([0.84090909, 0.62790698, 0.69767442, 0.69767442, 0.76744186,
       0.76744186])

### Testing of model by feeding new inputs

In [36]:
input_sample=(1,55,1,1,1,140,90,100,1,220,150,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,18,17,0,1,0,0,0,0)
input_np_array=np.asarray(input_sample)

In [37]:
X.columns

Index(['Gender', 'Age', 'Chest pain', 'Shortness of breath', 'Fatigue',
       'Systolic', 'Diastolic', 'Heart rate (bpm)', 'Lung sounds',
       'Cholesterol level (mg/dL)', 'LDL level (mg/dL)', 'HDL level (mg/dL)',
       'Diabetes', 'Atrial fibrillation', 'Mitral valve prolapse',
       'Rheumatic fever', 'Mitral stenosis', 'Aortic stenosis',
       'Tricuspid stenosis', 'Pulmonary stenosis', 'Dilated cardiomyopathy',
       'Hypertrophic cardiomyopathy', 'Restrictive cardiomyopathy',
       'Arrhythmogenic right ventricular cardiomyopathy',
       'Takotsubo cardiomyopathy', 'Drug use', 'Fever', 'Chills', 'Joint pain',
       'Alcoholism', 'Hypertension', 'Fainting', 'Dizziness', 'Smoking',
       'High cholesterol', 'Echocardiogram', 'Blood culture', 'EKG',
       'Cardiac CT', 'Obesity', 'Murmur', 'Chest x-ray', 'Previous illnesses',
       'Pulmonary function tests', 'Spirometry'],
      dtype='object')

In [38]:
input_reshape=input_np_array.reshape(1,-1)

In [39]:
input_reshape

array([[  1,  55,   1,   1,   1, 140,  90, 100,   1, 220, 150,  40,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   1,   0,   0,   1,   1,   0,   0,  18,  17,
          0,   1,   0,   0,   0,   0]])

In [40]:
prediction = ranforcls.predict(input_reshape)
prediction

c:\users\acer\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [41]:
result = prediction.astype(int)
result

array([0])

In [42]:
df1=pd.read_csv(r"E:\medical hackathon\Dignosis.csv")
df1

Coronary artery disease (CAD)  Mitral regurgitation  Mitral stenosis  \
0                              0                     1                2   

   Aortic stenosis  Tricuspid stenosis  Pulmonary stenosis  \
0                3                   4                   5   

   Dilated cardiomyopathy  Hypertrophic cardiomyopathy  \
0                       6                            7   

   Restrictive cardiomyopathy  \
0                           8   

   Arrhythmogenic right ventricular cardiomyopathy  ...  \
0                                                9  ...   

   Acute native valve endocarditis  Subacute native valve endocarditis  \
0                               21                                  22   

   Infective endocarditis on prosthetic valve  Candidal endocarditis  \
0                                          23                     24   

   Native valve endocarditis involving multiple valves  \
0                                                 25     

   Primary pulmonary hypertension  \
0                              26   

   Secondary pulmonary hypertension due to COPD  \
0                                            27   

   Secondary pulmonary hypertension due to obesity and sleep apnea  \
0                                                 28                 

   Secondary pulmonary hypertension due to scleroderma  \
0                                                 29     

   Secondary pulmonary hypertension due to chronic thromboembolic disease  
0                                                 30                       

[1 rows x 31 columns]

In [43]:
print("Person is suffering from", df1.iloc[:,prediction.astype(int)].columns[0])

Person is suffering from Coronary artery disease (CAD)
